name: CI Test
on: ['pull_request']

jobs:
  prepare:
    runs-on: ubuntu-latest
    name: ci
    services:
      verdaccio:
        image: verdaccio/verdaccio:5
        ports:
          - '4873:4873'
        volumes:
          - './verdaccio:/verdaccio/conf'
  test:
      name: Test generator as dependency with Node ${{ matrix.node }}
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node: [ '12', '14', '16', '18' ]
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3
        - name: Run test
          run: NODE_IMAGE_TAG=${{ matrix.node }} docker-compose up --abort-on-container-exit --remove-orphans
          working-directory: ./test/test-project