name: CI Test

on:
  pull_request:
    branches:
      - '*'

jobs:
  prepare:
    runs-on: ubuntu-latest
    name: ci
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

  run-test:
    needs: prepare
    runs-on: ubuntu-latest
    name: Run test
    container:
      image: verdaccio/verdaccio:5
    ports:
      - '4873:4873'
    strategy:
      matrix:
        node: ['12', '14', '16', '18']
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3
        - name: Run test
          run: NODE_IMAGE_TAG=${{ matrix.node }} docker-compose up --abort-on-container-exit --remove-orphans
          working-directory: ./test/test-project
