name: CI Test

on: ['pull_request']
jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      super-cli: ${{ steps.set-crashers-count.outputs.super-cli }}
    name: ci
    services:
      verdaccio:
        image: verdaccio/verdaccio:5
        ports:
          - 4873:4873
        volumes:
          - './verdaccio/conf:/verdaccio/conf:z'
          - './verdaccio/storage:/verdaccio/storage:z'
    steps:
    - uses: actions/checkout@v3
      options: --user root
    - name: Use Node
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: Install
      run: npm install
    - name: Testing Registry
      run: npm run test:registry
      working-directory: ./test/test-project
