# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: ['pull_request']
  # Allows you to run this workflow manually from the Actions tab


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  prepare:
        runs-on: ubuntu-latest
        name: ci
        services:
          verdaccio:
            image: verdaccio/verdaccio:5
            container_name: 'verdaccio'
            ports:
              - '4873:4873'
            volumes:
              - './verdaccio:/verdaccio/conf'

  s
